# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brenton's Tid-Bits
email: brentonhorne77@gmail.com
description: Where Brenton stores his updates
baseurl: ""
url: "https://fusion809.github.io"
twitter_username: fusion809
github_username:  fusion809

# Build settings
markdown: kramdown
